name: hakatime

on:
  release:
    types: [published]
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-amd64-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.docker-tags.outputs.tags }}
      labels: ${{ steps.docker-tags.outputs.labels }}
      json: ${{ steps.docker-tags.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker tags
        id: docker-tags
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/mujx/hakatime
          tags: |
            type=semver,pattern=v{{version}}

  setup-arm-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.docker-tags.outputs.tags }}
      labels: ${{ steps.docker-tags.outputs.labels }}
      json: ${{ steps.docker-tags.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker tags
        id: docker-arm-tags
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/mujx/hakatime
          tags: |
            type=semver,pattern=v{{version}}-arm

  push-amd64:
    runs-on: ubuntu-latest
    needs:
    - setup-amd64-tags
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     registry: docker.io
      #     username: mujx
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: false
          context: ./
          tags: ${{ needs.setup-amd64-tags.outputs.tags }}
          labels: ${{ needs.setup-amd64-tags.outputs.labels }}

  push-arm:
    runs-on: ubuntu-latest
    needs:
    - setup-arm-tags
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     registry: docker.io
      #     username: mujx
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.arm
          platforms: linux/arm/v7
          push: false
          context: ./
          tags: ${{ needs.setup-arm-tags.outputs.tags }}
          labels: ${{ needs.setup-arm-tags.outputs.labels }}
